apiVersion: v1
kind: List
items:

- kind: BuildConfig
  apiVersion: 'v1'
  metadata:
    name: 'ubi8-rails' 
  spec:
    
    runPolicy: 'Serial' 
    
    triggers: 
      - type: 'GitHub'
        github:
          secret: 'base'
      - type: 'Generic'
        generic:
          secret: 'base'
      - type: 'ImageChange'
    
    source: 
      git:
        uri: 'https://github.com/majordomusio/openshift-ubi.git'
        ref: 'master'
      contextDir: 'rails/6.0'
    
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile.rhel8
        forcePull: true
    
    output:
      to:
        kind: ImageStreamTag
        name: 'ubi8-rails:6.0'
        namespace: openshift

- kind: ImageStream
  apiVersion: 'v1'
  metadata:
    annotations:
      description: RAILS base image for everything
      tags: ruby rails
    name: 'ubi8-rails'
    namespace: openshift