apiVersion: v1
kind: List
items:

- kind: BuildConfig
  apiVersion: 'v1'
  metadata:
    name: 'fupas-rails5'
    annotations:
      description: RAILS 5.2 base image for everything
      tags: ruby rails
    labels:
      runtime: ruby
  spec:
    
    runPolicy: 'Serial' 
    
    triggers: 
      - type: 'GitHub'
        github:
          secret: 'base'
      - type: 'Generic'
        generic:
          secret: 'base'
      - type: 'ImageChange'
    
    source: 
      git:
        uri: 'https://github.com/fupas/fupas-ubi.git'
        ref: 'master'
      contextDir: 'rails'
    
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: 5/Dockerfile
        forcePull: true
    
    output:
      to:
        kind: ImageStreamTag
        name: 'fupas-rails5:5.2'
        #namespace: openshift

- kind: ImageStream
  apiVersion: 'v1'
  metadata:
    name: 'fupas-rails5'
    annotations:
      description: RAILS5 base image for everything
      tags: ruby rails
    labels:
      runtime: ruby
    #namespace: openshift