apiVersion: v1
kind: List
items:

- kind: ImageStream
  apiVersion: 'v1'
  metadata:
    annotations:
      description: rails-bootstrap starter app
      tags: ruby, rails, bootstrap
    labels:
      app: rails-bootstrap
    name: rails-bootstrap

- kind: BuildConfig
  apiVersion: 'v1'
  metadata:
    labels:
      app: rails-bootstrap
    name: rails-bootstrap
  spec:
    successfulBuildsHistoryLimit: 2
    failedBuildsHistoryLimit: 1
    runPolicy: 'Serial' 
    
    triggers:
    - github:
        secret: rails-bootstrap
      type: GitHub
    - generic:
        secret: rails-bootstrap
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
      
    source:
      git:
        uri: https://github.com/ratchetcc/rails-bootstrap
        ref: master
      type: Git
    
    strategy:
      sourceStrategy:
        env:
          # database, user etc
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                key: database-name
                name: rails-bootstrap-secrets
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: rails-bootstrap-secrets
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: rails-bootstrap-secrets
                
          # RAILS
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                key: keybase
                name: rails-bootstrap-secrets

          - name: REQUIRE_RAILS_MASTER_KEY
            value: 'false'
            
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                key: rails-master-key
                name: rails-bootstrap-secrets

          - name: WEBPACKER
            value: 'stimulus'

        from:
          kind: ImageStreamTag
          namespace: openshift
          name: 'ubi8-rails:6.0'
          
      type: Source
        
    output:
      to:
        kind: ImageStreamTag
        name: 'rails-bootstrap:latest'
